name: libasm tester

on:
  push:
    branches: [ current_project ]
  pull_request:
    branches: [ current_project ]

strategy:
  matrix:
    compiler: [gcc, clang]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run CMake
        env:
          CC: ${{ matrix.compiler }}
          run: make
