name: libft tester

on:
  push:
    branches: [ current_project ]
  pull_request:
    branches: [ current_project ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: sudo apt-get update
      - name: Debug
        run: make
      - name: Check leaks
        run: |
            ./yoo
